### ISSUE TITLE
Enter your Xiaomi Account and Password ??

### ISSUE THREAD

**Issue by fmonzzone** [tsunglung/XiaomiAirFryer#6]
Setup: **"2. Enter your Xiaomi Account and Password"** never ask me for credentials

**Comment by Szlatkovszky** [comment]
I have the am problem, could you solve it?

**Comment by Szlatkovszky** [comment]
> Setup: **"2. Enter your Xiaomi Account and Password"** never ask me for credentials

You have to search for Xiaomi Miio in the COnfiguratioan--»Integration»»Add Integration there you can login.
Unfortunately i get en error that the device modell is not known...

**Comment by fmonzzone** [comment]
Thank you :D
